// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview'
        }
      ]
    },
    {
      type: 'category',
      label: 'Course Structure',
      items: [
        {
          type: 'autogenerated',
          dirName: 'weekly-breakdown'
        },
        {
          type: 'autogenerated',
          dirName: 'learning-outcomes'
        }
      ]
    },
    {
      type: 'category',
      label: 'Hardware & Setup',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hardware'
        }
      ]
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'doc',
          id: 'modules/module-1',
          label: 'Module 1: The Robotic Nervous System (ROS 2)'
        },
        {
          type: 'doc',
          id: 'modules/module-2',
          label: 'Module 2: The Digital Twin (Gazebo & Unity)'
        },
        {
          type: 'doc',
          id: 'modules/module-3',
          label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)'
        },
        {
          type: 'doc',
          id: 'modules/module-4',
          label: 'Module 4: Vision-Language-Action (VLA)'
        }
      ]
    },
    {
      type: 'category',
      label: 'Assessments & Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'assessments'
        },
        {
          type: 'autogenerated',
          dirName: 'technical-examples'
        }
      ]
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        {
          type: 'doc',
          id: 'capstone/index',
          label: 'The Autonomous Humanoid'
        }
      ]
    },
  ]
};

module.exports = sidebars;