from dataclasses import dataclass
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class BookContent:
    """
    Represents the text extracted from Docusaurus book pages, including clean text content,
    source URL, chapter/section information, and text position within the document.
    """
    url: str
    title: str
    content: str
    chapter: Optional[str] = None
    section: Optional[str] = None
    text_position: Optional[int] = None
    created_at: datetime = datetime.now()
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class TextChunk:
    """
    Represents a segment of book content that fits within Cohere embedding model input limits,
    with metadata about its original location and context.
    """
    id: str
    content: str
    source_url: str
    chapter: Optional[str] = None
    section: Optional[str] = None
    chunk_index: int = 0
    total_chunks: int = 1
    created_at: datetime = datetime.now()
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class Embedding:
    """
    Represents the vector representation of a text chunk generated by Cohere models,
    with associated metadata for retrieval.
    """
    id: str
    vector: List[float]
    text_chunk: TextChunk
    created_at: datetime = datetime.now()
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class QdrantCollection:
    """
    Represents the storage container in Qdrant Cloud Free Tier where embeddings
    and their metadata are persisted.
    """
    name: str
    size: int  # Dimension of the vectors
    distance: str = "Cosine"  # Distance metric for similarity search
    created_at: datetime = datetime.now()
    metadata: Optional[Dict[str, Any]] = None